include:
  - ./docker-compose-base.dev.yml

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - ${CONSOLE_HTTP_PORT}:80
      - ${CONSOLE_HTTPS_PORT}:443
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ../docker/nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ../docker/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./entrypoint.dev.sh:/ragflow/entrypoint.sh
      - ./service_conf.dev.yaml.template:/ragflow/conf/service_conf.yaml.template 
    env_file: .env.dev
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - WS=${WS}
      - HOST=${RAGFLOW_NETWORK_HOST}
      - MYSQL_HOST=${RAGFLOW_NETWORK_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - REDIS_HOST=${RAGFLOW_NETWORK_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MINIO_HOST=${RAGFLOW_NETWORK_HOST}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
      - ES_HOST=${RAGFLOW_NETWORK_HOST}
      - ES_PORT=${ES_PORT}
      - INFINITY_HOST=${RAGFLOW_NETWORK_HOST}
      - INFINITY_THRIFT_PORT=${INFINITY_THRIFT_PORT}
      - INFINITY_HTTP_PORT=${INFINITY_HTTP_PORT}
      - INFINITY_PSQL_PORT=${INFINITY_PSQL_PORT}
    networks:
      - ragflow
    restart: on-failure
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['1']
  # executor:
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   image: ${RAGFLOW_IMAGE}
  #   container_name: ragflow-executor
  #   volumes:
  #     - ./ragflow-logs:/ragflow/logs
  #     - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
  #   env_file: .env
  #   environment:
  #     - TZ=${TIMEZONE}
  #     - HF_ENDPOINT=${HF_ENDPOINT}
  #     - MACOS=${MACOS}
  #   entrypoint: "/ragflow/entrypoint_task_executor.sh 1 3"
  #   networks:
  #     - ragflow
  #   restart: on-failure
  #   # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
  #   # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
